name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: git clone https://github.com/niuyuling/cproxy.git  
git clone https://github.com/ndevilla/iniparser.git  
cd iniparser  
make  
cd ../cproxy  
make clean; make  
